-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here

-- local map = vim.keymap.set
--
-- map("n", "<leader>fT", function()
--   Snacks.terminal({ "zsh" }, { win = { position = "right" } })
-- end, { desc = "Terminal (cwd)" })
-- map("n", "<leader>ft", function()
--   Snacks.terminal({ "zsh" }, { cwd = LazyVim.root() }, { win = { position = "right" } })
-- end, { desc = "Terminal (Root Dir)" })
