theme = "base16_terminal"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
C-r = ":config-reload"

[editor]
true-color = true
line-number = "relative"
bufferline = "multiple"
color-modes = true
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 0

[editor.inline-diagnostics]
cursor-line = "hint" # show warnings and errors on the cursorline inline
